### ISSUE TITLE
Request for 3.10 wheels for windows

### ISSUE THREAD

**Issue by krpatter-intc** [mardiros/lastuuid#1]
Seems that 3.10 wheels for windows (but other playforms) are not posted to pypi (but 3.11 and 3.12 are). Can you add 3.10 wheels for windows (64bit) ?

**Comment by mardiros** [comment]
I've make a release 0.1.2 for simplicity with those new builds:


https://pypi.org/project/lastuuid/#lastuuid-0.1.2-cp310-cp310-win_amd64.whl

https://pypi.org/project/lastuuid/#lastuuid-0.1.2-cp310-cp310-win32.whl
